Test: SynapseRouterV2 Integration
synapsecns/synapse-contracts pull request #292
Opened 2023-09-25 19:30 UTC by mikeyrf

## Description

Integration tests on a few chains for `SynapseRouterV2.sol`.

## Checklist

- [ ] New Contracts have been tested
- [ ] Lint has been run
- [ ] I have checked my code and corrected any misspellings

2023-10-03 20:54 UTC, mikeyrf commented
@ChiTimesChi core of Router V2 integration tests is finished, so could use an initial review. The Arbitrum implementation only considers expected tokens for nUSD related pool (USD stablecoin bridging) with CCTP and Synapse bridge modules. Can add more bridge tokens if you like to this as well.

2023-10-12 21:40 UTC, mikeyrf commented
@ChiTimesChi refactor finished and ready for review for you.

2023-10-13 14:18 UTC, ChiTimesChi requested changes
Tests look great, nice work! Requesting some final changes, then it should be good to go for the Arbitrum tests :rocket:

2023-10-13 14:18 UTC, ChiTimesChi commented on test/utils/IntegrationUtils.sol
> +    }
With pragma 0.8.17 `block.chainid` could be used instead of wrapping this into a function

2023-10-16 12:49 UTC, mikeyrf commented on test/router/v2/integration/SynapseRouterV2.Integration.Arbitrum.t.sol
> +        tokenSymbols[0] = "CCTP.USD";
Good catch ty!

2023-10-17 18:51 UTC, mikeyrf commented
@ChiTimesChi Ready for final go ahead then can merge 🖖

2023-10-17 19:28 UTC, ChiTimesChi approved these changes
Very solid job! LGTM

2023-10-17 19:30 UTC, merged